function FileData_Pairs(x)
{
x.t("aors","users");
x.t("dashboards","checking");
x.t("create","views");
x.t("discovering","fabric");
x.t("policies","create");
x.t("notifications","configure");
x.t("checking","fabric");
x.t("aaa","services");
x.t("setup","configuration");
x.t("initial","setup");
x.t("configuration","discovering");
x.t("configuration","initial");
x.t("services","configure");
x.t("configure","aaa");
x.t("configure","maps");
x.t("configure","service");
x.t("configure","roles");
x.t("maps","policies");
x.t("users","configure");
x.t("service","notifications");
x.t("fabric","status");
x.t("fabric","configure");
x.t("roles","aors");
x.t("views","dashboards");
}
