function FileData_Pairs(x)
{
x.t("table","displays");
x.t("table","behavior");
x.t("topic","transitioning");
x.t("displays","behavior");
x.t("rediscover","multiple");
x.t("rediscover","fabric");
x.t("time","rediscover");
x.t("time","parent");
x.t("time","turn");
x.t("multiple","fabrics");
x.t("advisor","table");
x.t("advisor","turn");
x.t("advisor","spectre");
x.t("network","advisor");
x.t("brocade","network");
x.t("comparison","transitioning");
x.t("comparison","following");
x.t("comparison","spectre");
x.t("bna","comparison");
x.t("parent","topic");
x.t("monitoring","multiple");
x.t("monitoring","fabric");
x.t("transitioning","brocade");
x.t("following","table");
x.t("turn","monitoring");
x.t("spectre","brocade");
x.t("spectre","bna");
x.t("fabrics","time");
x.t("fabric","time");
x.t("behavior","comparison");
}
